version: '3.7'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.7-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks: 
      - microservice_network
volumes:
  rabbitmq_data:
networks: 
  microservice_network:
