version: '3.7'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.7-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks: 
      - microservice_network
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.26
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - microservice_network
volumes:
  rabbitmq_data:
networks: 
  microservice_network:
