apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-depl
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:8.1.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - name: grafana-http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000

