apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-depl
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-cm
            items:
              - key: prometheus.yml
                path: prometheus.yml
      containers:
      - name: prometheus
        image: prom/prometheus:v2.30.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--storage.tsdb.path=/prometheus"
          - "--storage.tsdb.retention=20d"
          - "--web.console.libraries=/usr/share/prometheus/console_libraries"
          - "--web.console.templates=/usr/share/prometheus/consoles"
        volumeMounts:
          - mountPath: /etc/prometheus/prometheus.yml
            name: prometheus-config
            subPath: prometheus.yml
        ports:
        - name: prometheus-http
          containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090

