rabbitmq:
  Host: localhost
  Port: 5672
  User: guest
  Password: guest
  Exchange: products-exchange
  Queue: products-queue
  RoutingKey: products-routing-key
  ConsumerTag: products-consumer
  WorkerPoolSize: 24
service:
  Port: 8080
jeager:
  Host: localhost:6831
  ServiceName: product_service
  LogSpans: false
metrics:
  Url: 0.0.0.0:7070
  ServiceName: product_service