apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      evaluation_interval: 10s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["0.0.0.0:9090"]